services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=dbsecurity'
      - 'MYSQL_PASSWORD=fjteigti'
      - 'MYSQL_ROOT_PASSWORD=ururfgyiuz'
      - 'MYSQL_USER=swino'
    ports:
      - '127.0.0.1:3306:3306'
